In [1]:
import numpy as np

### Convert Python list

In [2]:
mylist = [1,2,3]

In [4]:
myarr = np.array(mylist)

In [5]:
type(myarr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

### Builtin functions to create numpy objects

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### evenly spaced numbers between start and stop

In [14]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

### identity matrix

In [15]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Random Distributions of Data

In [16]:
np.random.rand(1)

array([0.32423965])

In [19]:
np.random.rand(4,5)

array([[0.51102565, 0.88856872, 0.66542671, 0.95769467, 0.70525632],
       [0.13456456, 0.2696343 , 0.54110558, 0.23807423, 0.32100742],
       [0.51277105, 0.8033499 , 0.01826106, 0.69732805, 0.78690138],
       [0.10491188, 0.48711595, 0.98819779, 0.64749138, 0.16397531]])

### standard normal distribution
https://www.scribbr.com/statistics/standard-normal-distribution/

In [21]:
np.random.randn(2,3)

array([[-0.41008408, -0.83595715,  0.15598253],
       [ 1.32837642, -1.35105103,  0.52621024]])

### random integers

In [27]:
np.random.randint(0,101,size=5)

array([56, 23, 35, 66, 88])

In [28]:
np.random.randint(0,101,size=(4,5))

array([[73, 77, 63, 29, 31],
       [47, 33, 45, 11, 79],
       [45, 48, 51, 32, 10],
       [29, 83, 85,  0, 51]])

### set seed for random numbers in order to reproduce results

In [30]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [31]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

### useful attributes and methods in numpy

In [37]:
arr = np.arange(0,25)

In [38]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

#### reshape as a 5x5

In [36]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

#### max or min

In [39]:
ranarr = np.random.randint(0,101,10)

In [40]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [41]:
ranarr.max()

99

In [42]:
ranarr.min()

2

#### get index location of max and min

In [43]:
ranarr.argmax()

5

In [44]:
ranarr.argmin()

7

#### get type of array

In [46]:
ranarr.dtype

dtype('int64')

#### get shape of array

In [48]:
arr.shape

(25,)

In [49]:
arr = arr.reshape(5,5)

In [50]:
arr.shape

(5, 5)